"""Channel 2: receive events the device pushes via httpHosts.

The device is configured to POST its events to a Home Assistant webhook URL.
That is real push, no polling.

Gotchas found against the hardware (see docs/protocol.md):

  - There is only **one** host slot. If an NVR or HikConnect already owns it,
    we warn instead of silently overwriting.
  - The URL is capped at **128 characters**.
  - To unconfigure, use **DELETE**: a PUT with an empty `<url></url>` is
    rejected with 400 badXmlFormat. The factory blank slot is generated by the
    firmware and cannot be recreated through the API.
"""

from __future__ import annotations

import json
import logging
from typing import Any

from .const import CALL_IDLE, CALL_ON_CALL, CALL_RING, HTTP_HOST_URL_MAX_LEN, HTTP_HOSTS
from .models import xml_to_dict

_LOGGER = logging.getLogger(__name__)


class HttpHostSlotInUse(Exception):
    """The single notification slot already points somewhere else."""

    def __init__(self, current: str) -> None:
        super().__init__(f"The httpHosts slot is already in use by {current}")
        self.current = current


def build_host_config(url_path: str, ip_address: str, port: int) -> str:
    """Build the XML that points the device at our webhook."""
    if len(url_path) > HTTP_HOST_URL_MAX_LEN:
        raise ValueError(
            f"The webhook URL is {len(url_path)} characters; "
            f"the device accepts at most {HTTP_HOST_URL_MAX_LEN}"
        )
    return (
        '<HttpHostNotificationList version="2.0" '
        'xmlns="http://www.isapi.org/ver20/XMLSchema">'
        '<HttpHostNotification version="2.0">'
        "<id>1</id>"
        f"<url>{url_path}</url>"
        "<protocolType>HTTP</protocolType>"
        "<parameterFormatType>JSON</parameterFormatType>"
        "<addressingFormatType>ipaddress</addressingFormatType>"
        f"<ipAddress>{ip_address}</ipAddress>"
        f"<portNo>{port}</portNo>"
        "<httpAuthenticationMethod>none</httpAuthenticationMethod>"
        "</HttpHostNotification>"
        "</HttpHostNotificationList>"
    )


def describe_existing_host(raw: bytes | str) -> str | None:
    """Return 'ip:port/path' if the slot is already configured, else None."""
    try:
        data = xml_to_dict(raw)
    # An empty slot returns ResponseStatus instead of the list.
    except Exception:
        return None

    entry = data.get("HttpHostNotificationList", {}).get("HttpHostNotification")
    if isinstance(entry, list):
        entry = entry[0] if entry else None
    if not isinstance(entry, dict):
        return None

    ip = entry.get("ipAddress", "")
    port = entry.get("portNo", "")
    url = entry.get("url", "")
    # The factory state is 0.0.0.0:0 with an empty url -- that counts as free.
    if not ip or ip == "0.0.0.0" or port in ("", "0"):
        return None
    return f"{ip}:{port}{url}"


async def configure_host(
    client, url_path: str, ip_address: str, port: int, *, force: bool = False
) -> None:
    """Point the device at our webhook.

    Raises HttpHostSlotInUse if another consumer already owns it, unless
    `force` is passed -- silently overwriting would break an NVR's recording
    without the user ever noticing.
    """
    try:
        current = await client.request("GET", HTTP_HOSTS, raw=True)
    # No entry at all means the slot is free.
    except Exception:
        current = b""

    existing = describe_existing_host(current)
    if existing and not force:
        ours = f"{ip_address}:{port}{url_path}"
        if existing != ours:
            raise HttpHostSlotInUse(existing)

    await client.request("PUT", HTTP_HOSTS, data=build_host_config(url_path, ip_address, port))


async def clear_host(client) -> None:
    """Remove the webhook configuration.

    DELETE, not a PUT with zeroed values -- see the module docstring.
    """
    await client.request("DELETE", HTTP_HOSTS)


# ----------------------------------------------------------------------
# Parsing what arrives
# ----------------------------------------------------------------------

# Keys where Hikvision firmwares hide the call state. It varies by model and
# format, so we look in several.
_STATUS_KEYS = ("status", "callStatus", "CallStatus", "eventState")

_EVENT_TO_STATUS = {
    "callstatus": None,  # the payload carries the state
    "doorbell": CALL_RING,
    "ring": CALL_RING,
}


def parse_push_event(body: bytes, content_type: str = "") -> dict[str, Any]:
    """Convert the device's POST into a normalised dict.

    Always returns at least {'raw': ...}; includes 'call_status' when it can
    be determined. Never raises -- an odd payload must not take the
    integration down, only fail to update state.
    """
    event: dict[str, Any] = {}

    stripped = body.lstrip()
    payload: Any = None
    if stripped[:1] in (b"{", b"["):
        try:
            payload = json.loads(body)
        except json.JSONDecodeError:
            payload = None
    elif stripped[:1] == b"<":
        try:
            payload = xml_to_dict(body)
        # A malformed payload must not break the integration.
        except Exception:
            payload = None

    if payload is None:
        event["raw"] = body[:2048].decode("utf-8", errors="replace")
        return event

    event["payload"] = payload

    flat = _flatten(payload)
    for key in ("eventType", "EventType", "eventDescription"):
        if key in flat:
            event["event_type"] = flat[key]
            break

    for key in _STATUS_KEYS:
        value = flat.get(key)
        if isinstance(value, str) and value in (CALL_IDLE, CALL_RING, CALL_ON_CALL):
            event["call_status"] = value
            break
    else:
        event_type = str(event.get("event_type", "")).lower()
        mapped = _EVENT_TO_STATUS.get(event_type)
        if mapped:
            event["call_status"] = mapped

    return event


def _flatten(data: Any, out: dict[str, Any] | None = None) -> dict[str, Any]:
    """Flatten nested dicts so keys can be found at any depth."""
    if out is None:
        out = {}
    if isinstance(data, dict):
        for key, value in data.items():
            if isinstance(value, (dict, list)):
                _flatten(value, out)
            else:
                out.setdefault(key, value)
    elif isinstance(data, list):
        for item in data:
            _flatten(item, out)
    return out
